

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: job_offer_db_2
      POSTGRES_USER: actual_username
      POSTGRES_PASSWORD: actual_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U actual_username"]
      interval: 10s
      timeout: 5s
      retries: 5

  job-offer-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-offer-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_offer_db_2
      SPRING_DATASOURCE_USERNAME: actual_username
      SPRING_DATASOURCE_PASSWORD: actual_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres_data:
