services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-new1
    environment:
      POSTGRES_DB: job_offer_db_1
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_offer_app_new1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_offer_db_1
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
    volumes:
      - jobOffersDescriptions:/app/jobOffersDescriptions

volumes:
  postgres-data:
    driver: local
  jobOffersDescriptions:
    driver: local
